### ISSUE TITLE
Site down!

### ISSUE THREAD

**Issue by ashleywr** [MayhemYDG/just-believe.in#2]
I'm sure not a lot of people still use the site, but just saw that it was down today compared to a couple days ago.

**Comment by MayhemYDG** [comment]
Loads fine for me, try hard-refreshing?

**Comment by ashleywr** [comment]
Strange! I checked on my phone and isitup and all three weren't working. Oh well, haha thanks.

**Comment by MayhemYDG** [comment]
Seems like DigitalOcean is having DNS connectivity issues, which should be resolved soon enough.

**Comment by MayhemYDG** [comment]
Everything should be fine now. Let me know otherwise.
